_commit: v1.1.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
repo_name: mopidy-alsamixer
dist_name: Mopidy-ALSAMixer
ext_name: alsamixer
github_username: mopidy
short_description: Mopidy extension for ALSA volume control
